export enum JOBPOSTCATEGORY {
  SOFTWARE_DEVELOPMENT = 'Software Development',
  WEB_DEVELOPMENT = 'Web Development',
  MOBILE_APP_DEVELOPMENT = 'Mobile App Development',
  FRONTEND_DEVELOPMENT = 'Frontend Development',
  BACKEND_DEVELOPMENT = 'Backend Development',
  FULLSTACK_DEVELOPMENT = 'Full Stack Development',
  DEVOPS = 'DevOps & Cloud',
  DATA_SCIENCE = 'Data Science',
  MACHINE_LEARNING = 'Machine Learning',
  ARTIFICIAL_INTELLIGENCE = 'Artificial Intelligence',
  CYBER_SECURITY = 'Cyber Security',
  QA_TESTING = 'QA & Testing',
  GAME_DEVELOPMENT = 'Game Development',
  AR_VR = 'AR / VR Development',
  BLOCKCHAIN = 'Blockchain Development',
  UI_UX = 'UI / UX Design',
  IT_SUPPORT = 'IT Support & Networking'
}


export enum JOBTITLE {
  // Software / Web
  SOFTWARE_ENGINEER = 'Software Engineer',
  SOFTWARE_DEVELOPER = 'Software Developer',
  WEB_DEVELOPER = 'Web Developer',

  // Frontend
  FRONTEND_DEVELOPER = 'Frontend Developer',
  ANGULAR_DEVELOPER = 'Angular Developer',
  REACT_DEVELOPER = 'React Developer',
  UI_ENGINEER = 'UI Engineer',

  // Backend
  BACKEND_DEVELOPER = 'Backend Developer',
  NODE_DEVELOPER = 'Node.js Developer',
  JAVA_BACKEND_DEVELOPER = 'Java Backend Developer',
  PYTHON_BACKEND_DEVELOPER = 'Python Backend Developer',

  // Fullstack
  FULLSTACK_DEVELOPER = 'Full Stack Developer',
  MERN_STACK_DEVELOPER = 'MERN Stack Developer',
  MEAN_STACK_DEVELOPER = 'MEAN Stack Developer',

  // Mobile
  ANDROID_DEVELOPER = 'Android Developer',
  IOS_DEVELOPER = 'iOS Developer',
  FLUTTER_DEVELOPER = 'Flutter Developer',
  REACT_NATIVE_DEVELOPER = 'React Native Developer',

  // DevOps / Cloud
  DEVOPS_ENGINEER = 'DevOps Engineer',
  CLOUD_ENGINEER = 'Cloud Engineer',
  AWS_ENGINEER = 'AWS Engineer',

  // Data / AI
  DATA_SCIENTIST = 'Data Scientist',
  DATA_ANALYST = 'Data Analyst',
  MACHINE_LEARNING_ENGINEER = 'Machine Learning Engineer',
  AI_ENGINEER = 'AI Engineer',

  // Security
  CYBER_SECURITY_ANALYST = 'Cyber Security Analyst',
  SECURITY_ENGINEER = 'Security Engineer',
  ETHICAL_HACKER = 'Ethical Hacker',

  // QA
  QA_ENGINEER = 'QA Engineer',
  SOFTWARE_TESTER = 'Software Tester',
  AUTOMATION_TEST_ENGINEER = 'Automation Test Engineer',

  // Design
  UI_DESIGNER = 'UI Designer',
  UX_DESIGNER = 'UX Designer',
  PRODUCT_DESIGNER = 'Product Designer',

  // Other
  GAME_DEVELOPER = 'Game Developer',
  BLOCKCHAIN_DEVELOPER = 'Blockchain Developer',
  IT_SUPPORT_ENGINEER = 'IT Support Engineer'
}



export const JOB_CATEGORY_TITLE_MAP: Record<JOBPOSTCATEGORY, JOBTITLE[]> = {
  [JOBPOSTCATEGORY.SOFTWARE_DEVELOPMENT]: [
    JOBTITLE.SOFTWARE_ENGINEER,
    JOBTITLE.SOFTWARE_DEVELOPER
  ],

  [JOBPOSTCATEGORY.WEB_DEVELOPMENT]: [
    JOBTITLE.WEB_DEVELOPER
  ],

  [JOBPOSTCATEGORY.FRONTEND_DEVELOPMENT]: [
    JOBTITLE.FRONTEND_DEVELOPER,
    JOBTITLE.ANGULAR_DEVELOPER,
    JOBTITLE.REACT_DEVELOPER,
    JOBTITLE.UI_ENGINEER
  ],

  [JOBPOSTCATEGORY.BACKEND_DEVELOPMENT]: [
    JOBTITLE.BACKEND_DEVELOPER,
    JOBTITLE.NODE_DEVELOPER,
    JOBTITLE.JAVA_BACKEND_DEVELOPER,
    JOBTITLE.PYTHON_BACKEND_DEVELOPER
  ],

  [JOBPOSTCATEGORY.FULLSTACK_DEVELOPMENT]: [
    JOBTITLE.FULLSTACK_DEVELOPER,
    JOBTITLE.MERN_STACK_DEVELOPER,
    JOBTITLE.MEAN_STACK_DEVELOPER
  ],

  [JOBPOSTCATEGORY.MOBILE_APP_DEVELOPMENT]: [
    JOBTITLE.ANDROID_DEVELOPER,
    JOBTITLE.IOS_DEVELOPER,
    JOBTITLE.FLUTTER_DEVELOPER,
    JOBTITLE.REACT_NATIVE_DEVELOPER
  ],

  [JOBPOSTCATEGORY.DEVOPS]: [
    JOBTITLE.DEVOPS_ENGINEER,
    JOBTITLE.CLOUD_ENGINEER,
    JOBTITLE.AWS_ENGINEER
  ],

  [JOBPOSTCATEGORY.DATA_SCIENCE]: [
    JOBTITLE.DATA_SCIENTIST,
    JOBTITLE.DATA_ANALYST
  ],

  [JOBPOSTCATEGORY.MACHINE_LEARNING]: [
    JOBTITLE.MACHINE_LEARNING_ENGINEER
  ],

  [JOBPOSTCATEGORY.ARTIFICIAL_INTELLIGENCE]: [
    JOBTITLE.AI_ENGINEER
  ],

  [JOBPOSTCATEGORY.CYBER_SECURITY]: [
    JOBTITLE.CYBER_SECURITY_ANALYST,
    JOBTITLE.SECURITY_ENGINEER,
    JOBTITLE.ETHICAL_HACKER
  ],

  [JOBPOSTCATEGORY.QA_TESTING]: [
    JOBTITLE.QA_ENGINEER,
    JOBTITLE.SOFTWARE_TESTER,
    JOBTITLE.AUTOMATION_TEST_ENGINEER
  ],

  [JOBPOSTCATEGORY.UI_UX]: [
    JOBTITLE.UI_DESIGNER,
    JOBTITLE.UX_DESIGNER,
    JOBTITLE.PRODUCT_DESIGNER
  ],

  [JOBPOSTCATEGORY.GAME_DEVELOPMENT]: [
    JOBTITLE.GAME_DEVELOPER
  ],

  [JOBPOSTCATEGORY.BLOCKCHAIN]: [
    JOBTITLE.BLOCKCHAIN_DEVELOPER
  ],

  [JOBPOSTCATEGORY.IT_SUPPORT]: [
    JOBTITLE.IT_SUPPORT_ENGINEER
  ],

  // categories without strict titles yet
  [JOBPOSTCATEGORY.AR_VR]: [],
};
