import { SECTOR } from './sector.enum';
import { DESIGNATION } from './designation.enum';

export const SECTOR_DESIGNATION_MAP: Record<SECTOR, DESIGNATION[]> = {

  /* ================= HR / RECRUITMENT ================= */
  [SECTOR.HUMAN_RESOURCES]: [
    DESIGNATION.HR_EXECUTIVE,
    DESIGNATION.HR_MANAGER,
    DESIGNATION.SENIOR_HR_PARTNER,
    DESIGNATION.DIRECTOR_HR
  ],

  [SECTOR.TALENT_ACQUISITION]: [
    DESIGNATION.TALENT_ACQUISITION,
    DESIGNATION.RECRUITMENT_MANAGER,
    DESIGNATION.HR_MANAGER,
    DESIGNATION.STAFFING_COORDINATOR
  ],

  [SECTOR.STAFFING_RECRUITMENT]: [
    DESIGNATION.STAFFING_COORDINATOR,
    DESIGNATION.RECRUITMENT_MANAGER,
    DESIGNATION.CLIENT_SUCCESS_MANAGER,
    DESIGNATION.OPERATIONS_MANAGER
  ],

  [SECTOR.HR_CONSULTING]: [
    DESIGNATION.SENIOR_HR_PARTNER,
    DESIGNATION.DIRECTOR_HR,
    DESIGNATION.FOUNDER
  ],

  /* ================= IT / ENGINEERING ================= */
  [SECTOR.SOFTWARE_DEVELOPMENT]: [
    DESIGNATION.TEAM_LEAD,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.DIRECTOR_ENGINEERING,
    DESIGNATION.CTO
  ],

  [SECTOR.INFORMATION_TECHNOLOGY]: [
    DESIGNATION.IT_HEAD,
    DESIGNATION.PROJECT_MANAGER,
    DESIGNATION.DELIVERY_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER
  ],

  [SECTOR.PRODUCT_ENGINEERING]: [
    DESIGNATION.PRODUCT_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.VP_TECHNOLOGY
  ],

  /* ================= DATA / CLOUD ================= */
  [SECTOR.DATA_AI]: [
    DESIGNATION.PRODUCT_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.CTO
  ],

  [SECTOR.CLOUD_DEVOPS]: [
    DESIGNATION.TEAM_LEAD,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.DIRECTOR_ENGINEERING
  ],

  [SECTOR.CYBER_SECURITY]: [
    DESIGNATION.IT_HEAD,
    DESIGNATION.CIO,
    DESIGNATION.DIRECTOR_ENGINEERING
  ],

  /* ================= BUSINESS TECH ================= */
  [SECTOR.FINTECH]: [
    DESIGNATION.PRODUCT_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.CTO,
    DESIGNATION.CIO
  ],

  [SECTOR.HEALTH_TECH]: [
    DESIGNATION.PRODUCT_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER,
    DESIGNATION.DIRECTOR_ENGINEERING
  ],

  [SECTOR.ED_TECH]: [
    DESIGNATION.PRODUCT_MANAGER,
    DESIGNATION.PROJECT_MANAGER,
    DESIGNATION.ENGINEERING_MANAGER
  ]
};
